const ROUTES = {
    ROOT:"/",
    ABOUT:"/about",
    CARDS:"/cards",
    SIGNUP:"/signup",
    LOGIN:"/login",
    MY_CARDS:"/my-cards",
    FAV_CARDS: "/fav-cards",
    SANDBOX:"/sandbox",
    CARD_DETAILS:"/card-info",
    CARD_EDIT:"/card-edit"

}


export const SANDBOX_ROUTES = {
  COMPONENT: "component",
  EVENTS:"events",
  MUI_SANDBOX:"mui-sandbox",
  DATA_MENU:'data-menu',
  LAYOUT_MENU:'layout-menu',
  NAVIGATION_MENU:'navigation-menu',
  PROPS_MENU:"props-menu",
  PROPS_OBJECT_MENU:'props-object menu',
  PROPS_STRING_MENU:'props-string menu',
  PROPS_TWO_KEYS_MENU:'props-two keys menu',
  USE_STATE_MENU:'use-state-menu',
  TEMPLATE: "template",
  LOGIC: "logic",
  STYLES: "styles",
  STYLE_MODULE:"style-module",
  SANDBOX_COMPONENTS: "sandbox-components",
  BABEL:"babel",
  STRING_INTERPOLATION:"string-interpolation",
  LOOPS:"loops",
  CONDITIONAL_RENDERING:"conditional-rendering",
  ONCLICK_JS:'onclick-js',
  ONCLICK_TS:'onclick-ts',
  RAISING_EVENTS_JS:'raising-events-js',
  RAISING_EVENTS_TS:'raising-events-ts',
  MUI_BUTTON:'mui-button',
  MUI_DIVIDER:'mui-divider',
  MUI_TYPOGRAPHY:"mui-typography",
  MUI_BOX:"mui-box",
  MUI_CONTAINER:"mui-container",
  MUI_GRID:"mui-grid",
  MUI_STACK:"mui-stack",
  MUI_APP_BAR:"mui-app-bar",
  MUI_BOTTOM_NAVIGATION:"mui-bottom-navigation",
  PROPS_TS:'props-ts',
  CHILD_PROPS_OBJECT:'child-props-object',
  FATHER_PROPS_OBJECT:'father-props-object',
  CHILD_PROPS_STRING:'child-props-string',
  FATHER_PROPS_STRING:'father-props-string',
   CHILD_PROPS_TWO_KEYS:'child-props-two keys',
  FATHER_PROPS_TWO_KEYS:'father-props-two keys',
  SET_POSTS:'set-posts',
  USE_STATE:'use-state',
  USE_STATE_ARRAY_OBJECTS:'use-state with array of objects',
  USE_STATE_COMPLEX_OBJECTS:'use-state with complex objects',
  USE_STATE_WITH_FUNCTIONS:'use-state with functions',
  USE_STATE_WITH_OBJECTS:'use-state with objects',
};

export default ROUTES;